info:
  component: Demo Api
  project:
      name: demo-api

server:
  port: 8081
  context-path: /demo-api

spring:
  application:
    name: demo-api
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: demo
    password: demo